config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts, only: [:new, :create, :index]
  
  
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnlyMicroverse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <div class="mb-0">
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %> </p>
    </div>
  <% end %>
   <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="notice"><%= alert %> </p>
    </div>
  <% end %>
  </div>
  <nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class="is-size-4">Members Only</h1>
    </a>
  </div>
     <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%if !user_signed_in? %>
            <%= link_to "Sing Up", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
         
         <%else %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-primary" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
</nav>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, 
                required: true,
                autofocus: true,
                label_html:{class:"label"}, input_html: { autocomplete: "name", class:"input" }, wrapper: false %>
    
    <%= f.input :body,
    required: true,
                autofocus: true,
                label_html:{class:"label"}, input_html: { autocomplete: "name", type:"textarea", class:"textarea" }, wrapper: false  %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"button is-info mt-2" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Posts
      </h1>
      <h2 class="subtitle">
      <%if user_signed_in? %>
        <%= link_to '+ New Post', new_post_path, class:"button is-info" %>
      <% else %>  
        Sign in or Sing up to create new posts and view authors
      <%end%>  
      </h2>
    </div>
  </div>
</section>

<div class="columns">
<div class="column is-half is-offset-one-quarter">
<% @posts.each do |post| %>

    <div class="box">
      <div class="media-content">
        <p class="title is-4 mb-1"><%= post.title %></p>
        <%if user_signed_in? %>
        <p class="subtitle is-6 has-text-info mt-0 mb-2">by <strong ><%= post.user.name %></strong></p>
        <% end %>
      </div>
    


      <%= post.body %>
    </div>

<% end %>
</div>




<br>

app/views/posts/new.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Create a new post
      </h1>
      <h2 class="subtitle">
      Share your story, your identity will be a secret!
      </h2>
    </div>
  </div>
</section>
<div class="columns">
<div class="column is-half is-offset-one-quarter ">

<%= render 'form', post: @post %>

</div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>